require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'cardeaholder',
        'Dev.Debug' => :debug,
        'Dev.Release' => :release

target 'cardeaholder' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'react-native-mrz', :path => '../node_modules/react-native-mrz'

  target 'cardeaholderTests' do
    inherit! :complete
    # Pods for testing
  end
end
