export const PrivacyPolicy = {
title: "Privacy Policy",
text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer finibus, ex at bibendum suscipit, lectus lectus imperdiet elit, non sollicitudin nunc lorem ut est. Nullam fermentum id ante blandit sagittis. Etiam convallis est eget dictum ultricies. Aenean velit est, rhoncus non tellus tincidunt, lacinia dignissim erat. Mauris tempus, orci at consequat pulvinar, diam nisi porta enim, a condimentum sem lorem at nisi. Donec sit amet augue quis tellus vulputate interdum. Sed a rutrum augue. Quisque pretium finibus orci id egestas. Vestibulum et laoreet nunc, a consequat justo. Praesent posuere augue quis urna placerat euismod. Donec viverra arcu eu consectetur consectetur. In nec blandit ipsum, vitae mattis nunc. In interdum libero lectus, et imperdiet nulla bibendum non. Sed feugiat tristique congue. Vestibulum imperdiet fringilla porta.

Maecenas vehicula eget orci eget luctus. Ut mattis eros eu congue semper. Nulla id feugiat sapien, quis blandit lectus. Morbi rutrum turpis mauris, in fermentum leo sollicitudin sed. Duis ornare bibendum tempor. Aenean lacinia mattis nisl, vitae tempor sapien consequat non. In vulputate pharetra vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus tincidunt lectus eu augue sodales, sed sollicitudin eros efficitur. Sed id mi congue, placerat magna in, placerat felis. Cras non dui velit. In quis tincidunt diam, a laoreet orci. Ut consectetur sagittis justo, vel tincidunt tellus rhoncus sed. Curabitur ultrices dapibus gravida. Donec tincidunt ipsum nibh, sodales finibus enim gravida in.

Maecenas vel nulla vel purus dignissim posuere a sed nulla. Suspendisse potenti. Mauris sit amet accumsan lectus. Duis ligula felis, malesuada eget interdum at, scelerisque eu lacus. Vivamus eu luctus massa, eget suscipit arcu. Sed pretium risus molestie, malesuada justo a, bibendum ante. Duis sed euismod elit.

Nullam molestie vel mi in dignissim. Integer in elit magna. Suspendisse blandit ex est, vel vestibulum justo pharetra id. Etiam quis tortor lectus. Nunc risus diam, maximus eget augue eu, condimentum faucibus nunc. Nullam imperdiet metus vel lorem laoreet, non maximus ex pretium. Integer aliquet, nisl a condimentum iaculis, nisl massa consequat tortor, nec feugiat eros quam et nunc. Phasellus est lectus, vestibulum at ipsum non, iaculis faucibus arcu. Nunc porttitor id dui id gravida. Maecenas sit amet leo posuere, scelerisque quam in, dignissim mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut tincidunt tellus consectetur eros scelerisque, quis volutpat urna consequat. Mauris ut nunc imperdiet, accumsan tellus eu, molestie elit. Suspendisse potenti.

Mauris eros massa, viverra sit amet fermentum et, porta sed nisi. Pellentesque a laoreet enim. In elementum dui sit amet tortor fringilla, in eleifend metus varius. Fusce sodales justo non arcu pulvinar volutpat. In auctor iaculis venenatis. In enim lectus, vestibulum vitae interdum nec, pulvinar at tellus. Sed auctor ullamcorper mauris et egestas.
`
}